" 
" User's local vim configuration
"  
" Developed by Lubomir Host 'rajo' <rajo AT platon.sk>
" Copyright (c) 2000-2005 Platon Group, http://platon.sk/
" All rights reserved.
"
" $Platon: vimconfig/vim/local/vimrc,v 1.6 2005-10-01 18:02:11 nepto Exp $

let g:company = "Platon Group, http://platon.sk/"

